### ISSUE TITLE
 Non-resolvable parent POM for org.springframework.cloud.stream.app:http-app-dependencies:2.0.0.BUILD-SNAPSHOT

### ISSUE THREAD

**Issue by komushi** [spring-cloud-stream-app-starters/http#15]
The following error happens when run

mvn clean install -PgenerateApps

```
Downloaded: http://repo.spring.io/release/org/springframework/session/spring-session-bom/Apple-SR1/spring-session-bom-Apple-SR1.pom (2.6 kB at 5.1 kB/s)
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.cloud.stream.app:http-app-dependencies:2.0.0.BUILD-SNAPSHOT: Could not find artifact org.springframework.cloud:spring-cloud-dependencies-parent:pom:2.0.0.BUILD-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 12, column 10
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.springframework.cloud.stream.app:http-app-dependencies:2.0.0.BUILD-SNAPSHOT (/Users/lleixu/Desktop/demo/http/http-app-dependencies/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.springframework.cloud.stream.app:http-app-dependencies:2.0.0.BUILD-SNAPSHOT: Could not find artifact org.springframework.cloud:spring-cloud-dependencies-parent:pom:2.0.0.BUILD-SNAPSHOT and 'parent.relativePath' points at no local POM @ line 12, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by artembilan** [comment]
@komushi ,

I have pushed some fix to the `master`, so you can pull the latest changes and try again to build the app locally.

Anyway I think the problem is just in the stale local Maven repo.

**Comment by komushi** [comment]
Thanks for your time checking this but it seems the issue still exists.

The steps are like below:

1. remove the local maven repository
2. "mvn clean install -PgenerateApps" => the above error will be reproduced here
3. re-run "mvn clean install -PgenerateApps" => apps generated successfully

So re-run can be the solution but still prefer to generateApps by one shot.

Thanks
